.PHONY: asus-g14
asus-g14: common
	stow -t ~ -d machines/asus-g14/ regolith

.PHONY: common
common: 
	stow -t ~ -d common/ broot
	stow -t ~ -d common/ alacritty
	stow -t ~ -d common/ home-manager
	stow -t ~ -d common/ vscode
	stow -t ~ -d common/ tmux
	stow -t ~ -d common/ spacemacs
