.PHONY: asus-g14
asus-g14: common
	stow -t ~ -d machines/asus-g14/ regolith

.PHONY: dell-g5
dell-g5: common
	stow -t ~ -d machines/dell-g5/ i3

.PHONY: common
common: 
	stow -D -t ~ -d common/ broot
	stow -D -t ~ -d common/ alacritty
	stow -D -t ~ -d common/ home-manager
	stow -D -t ~ -d common/ vscode
	stow -D -t ~ -d common/ tmux
	stow -D -t ~ -d common/ spacemacs
